name: Compile LaTeX to PDF

on:
  push:
    paths:
      - '**/*.tex'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up LaTeX
        uses: xu-cheng/latex-action@v2
        with:
          pdf_file: shaon_rahman_cv.pdf

      - name: Compile LaTeX
        run: |
          pdflatex -interaction=nonstopmode -halt-on-error -file-line-error -synctex=1 shaon_rahman_cv.tex
        env:
          PDFLATEX: pdflatex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v2
        with:
          name: compiled-pdf
          path: shaon_rahman_cv.pdf
